### ISSUE TITLE
Review Lifecycle model

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-security#138]
The lifecycle model in chapter 2 appears to (unintentionally) apply constraints on devices,
which may not be applicable by all devices.
The immediate problem is that it does not contain an end of life state,
but just assumes that a device, that has been decommissioned is considered
as a newly manufactured device, that can be easily reprovisioned.

Unfortunately this is not the case in some application scenarios,
see for example https://www.researchgate.net/publication/327809486_IoT_Device_Lifecycle_-_A_Generic_Model_and_a_Use_Case_for_Cellular_Mobile_Networks,
where a device is in an end-of-life state.

I quickly skimmed through the guideline document trying to find where the
lifecycle model or the lifecycle states are actually used.
There appears to be no strong dependency from the model in chapter 2,
so we could make section 2 an informative section and call it "Sample Lifecycle of a WoT Device".

**Comment by mmccool** [comment]
The intention was to move the lifecycle definitions to architecture where it belongs.   That never happened, unfortunately.   But as a short-term fix we certainly could add an end-of-life state, and/or just cite a suitable external reference for the lifecycle (although one for IoT rather than for mobile phones would be better... I've been meaning to look again at the IIC definitions, but these don't necessarily include Smart Home use cases, which need to take into account transfer of ownership, provisioning by external parties, and so forth...).

**Comment by mmccool** [comment]
Calling it a "sample lifecycle" would be OK.   Note the entire document is meant to be informative, though.  The dependencies are mainly in the form of scope, i.e. we focus primarily on the "Operational" state, and need to define what that is.  In various places though we also need to talk about Provisioning and Updates.

**Comment by mlagally** [comment]
@mmccool Yes, "Sample lifecycle" makes it clear that the diagram serves as an illustration and does not enforce anything.

**Comment by mmccool** [comment]
The Thing lifecycle may also be related to the information lifecycle especially for ID mutation, which is necessary to preserve privacy.   For example, the ID should be created/deleted when the Thing is onboarded/offboarded.  See also https://github.com/w3c/wot-security/issues/136

**Comment by mmccool** [comment]
This seems to have been superceded by https://github.com/w3c/wot-security/issues/169, which has been closed.  As discussed in the Security meeting on 2020.09.21, that means we can close this issue also (although we might create new, more specific issues in the future for future revisions to the lifecycle, in particular on the information lifecycle).
