### ISSUE TITLE
Misleading reference [IETFACE]

### ISSUE THREAD

**Issue by OliverPfaff** [w3c/wot-security#146]
The reference to [IETFACE] seems to be misleading as of now:
- The actual link points to the landing page of the WG (https://tools.ietf.org/wg/ace/) - via an indirection   
- The attached text promises "This document also defines a generic IoT security architecture that is followed by several IoT standards" (I am not yet aware of a [single] document/draft in the scope of the ACE WG that would deliver this as of now)

**Comment by ereshetova** [comment]
I think we really need to clean up our references, we have way too many, and we loose track of them as a result...

**Comment by mmccool** [comment]
Let's fix the minor issue (PR to be created by @OliverPfaff) and then create (or resurrect) an issue to look at the references.

**Comment by mmccool** [comment]
Need to make PR against wot-security master branch so we can review.

**Comment by mmccool** [comment]
Oliver is working on a PR.

**Comment by OliverPfaff** [comment]
Unassigned myself (done)

**Comment by mmccool** [comment]
Confirmed updated text and reference.
