### ISSUE TITLE
Consider OAuth2 "device" flow

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#173]
There is a new OAuth2 flow for devices that we may want to consider supporting, the "device" flow.  Review and make a decision.

**Comment by zolkis** [comment]
Then update on https://github.com/w3c/wot-scripting-api/issues/214

**Comment by mmccool** [comment]
There is a PR for this now that we plan to merge this week:https://github.com/w3c/wot-thing-description/pull/927

**Comment by mmccool** [comment]
Device flow has been added, and has been merged into TD spec 1.1 draft.   Note: we do need two implementations however before it can make it into REC.
