### ISSUE TITLE
Review oAuth2.0 use case

### ISSUE THREAD

**Issue by relu91** [w3c/wot-security#177]
In today's architecture call PR https://github.com/w3c/wot-architecture/pull/517 was closed. However, the document might still need an in-depth review. Please find the new oAuth use case document [here](https://github.com/w3c/wot-usecases/blob/master/USE-CASES/oauth.md)

**Comment by mmccool** [comment]
I note the privacy section is empty and that should probably be updated to point to the corresponding section in the OAuth2 spec.  Other than that, does anyone have any further comments?   If none I suggest we close in the next meeting.

**Comment by mmccool** [comment]
Closing, last recommended edit to be handled via https://github.com/w3c/wot-usecases/issues/49
