### ISSUE TITLE
Updates to "Security and Privacy Guidelines" (omnibus)

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#209]
The "Security and Privacy Guidelines" document has not been updated for a couple years and should be to take account of the new assertions in the new deliverables, and the removal of the Best Practices document (see Issue #208).

See also See also [TAG Review of Architecture](https://github.com/w3ctag/design-reviews/issues/736)

**Comment by mmccool** [comment]
As suggested by @j1y3p4rk I have started a PR were we can collect suggested changes and review comments: [PR 210](https://github.com/w3c/wot-security/pull/210).

To create the PR I had to make a minor change to the doc, so I added a comment the HTML header.  We can remove it before merging assuming we make other changes.

**Comment by mmccool** [comment]
Some things I noticed need fixing:
- Says WoT is declarative, not prescriptive, but some parts now prescriptive
- Does not mention Discovery at all
- Mentions DoS as a threat, but not DDoS
- Intro section is quite weak, does not define security, and ignores privacy
- Lifecycle needs to be aligned with Arch (or just reference it)

**Comment by mmccool** [comment]
- No references after 2019 (of course), things like OWASP guidelines are published annually
- Should reference protocol bindings for other protocols rather than focusing on CoAP/HTTP/MQTT
- No mention of DID, SSI, other key distribution mechanisms

**Comment by mmccool** [comment]
Discussion in Security TF call Jan 30:
- End-to-end security mentions TD signing, but we have no good way to do that
- "Secure practices for..." is a bit redundant, can simplify titles
- "Requirements" section is not really requirements, consider a different name (perhaps "Analysis")
- Protocol-specific comments in secure transport really about TLS/DTLS, which are a separate layer from protocols (e.g. can have OPC UA over these secure transports, too...)
- Need to refactor to figure what goes where in new charter; a lot of overlap with security and privacy considerations in other documents, lifecycle is out of place, etc.
- Can we fix anything in this charter, or do we have to wait until the next charter?
- Quick fixes: 
      - Update references, esp IETF versions, OWASP, e.g. things that are normally updated
      - Mention new deliverables - Discovery & Profiles, and Arch 1.1 and TD 1.1
      - Revise abstract to be more in line with Architecture wrt "descriptive" vs. "prescriptive", and generally position the document better
      - Expand the (currently very short) into
      - Rename "Requirements" section
      - Add DDoS threat
      - See what's going on with Lifecycle; was it supposed to have been moved to Arch and we just didn't delete it here yet?

**Comment by mmccool** [comment]
Other:
- Maybe add a workitem to "align security and privacy considerations across deliverables" to next WG charter?  These should be aligned with the "best practices" mentioned in the S&P Guidelines.  In the short term, probably can't do that justice with a full reorg, but we should at least check for contradictions and fix them.

**Comment by j1y3p4rk** [comment]
Additional comments: 
- Need to update 'Chapter 5, References to Existing Security Best Practices'. As written in EDITOR'S NOTE, we don't need to have all references listed. 
- In chapter 7.1, I suggest to change 

> In case it is not possible to pre-provision any of the types of credentials described above during the network setup phase or if the WoT Thing wants to use a more fine-grained access control policy on the WoT Interfaces it is exposing (for example, different controls might require different levels of authorization), the following methods can be used instead:

to 

> If the WoT Thing wants to use a fine-grained access control policy on the WoT Interfaces it is exposing (for example, different controls might require different levels of authorization), the following methods can be used instead:

as the types of credentials described above are nothing to do with access control.

**Comment by mmccool** [comment]
Survey of Risks mentioned in various deliverables - we should make sure these are consistent with the Threats in the guidelines document (at least one is missing, DDoS):

Discovery:
* Security
    * [8.1Denial of Service](https://w3c.github.io/wot-discovery/#security-consideration-dos)
    * [8.2Amplification and Distributed Denial of Service](https://w3c.github.io/wot-discovery/#security-consideration-amp-ddos)
    * [8.3Self-Discovery on LANs](https://w3c.github.io/wot-discovery/#security-consideration-lan-self-discovery)
* Privacy 
    * [9.1Location Tracking and Profiling](https://w3c.github.io/wot-discovery/#privacy-consideration-location-tracking)
    * [9.2Query Tracking](https://w3c.github.io/wot-discovery/#privacy-consideration-query-tracking)

Thing Description
* Security
   * [TD Interception and Tampering](https://w3c.github.io/wot-thing-description/#sec-security-consideration-TD-tampering)
   * [10.2Context Interception and Tampering](https://w3c.github.io/wot-thing-description/#sec-security-consideration-context-tampering)
   * [10.3Limited Duration Accesses](https://w3c.github.io/wot-thing-description/#security-consideration-access-duration)
   * [10.4Vulnerability Auditing](https://w3c.github.io/wot-thing-description/#sec-security-consideration-vulnerability-auditing)
   * [10.5Script Injection](https://w3c.github.io/wot-thing-description/#sec-security-consideration-script-injection)
   * [10.6JSON Parsing](https://w3c.github.io/wot-thing-description/#sec-security-consideration-execution)
   * [10.7JSON-LD Expansion](https://w3c.github.io/wot-thing-description/#sec-security-consideration-jsonld-expansion)
* Privacy 
   * [11.1 Context Fetching](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-context)
   * [11.2 Immutable Identifiers](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-id)
   * [11.3 Fingerprinting](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-fingerprint)
   * [11.4 ID Metadata](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-id-metadata)
   * [11.5 Globally Unique Identifiers](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-global-id-risk)
   * [11.6 Inferencing of Personally Identifiable Information](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-inferencing)

Architecture
* Security 
    * [10.1WoT Thing Description Risks](https://w3c.github.io/wot-architecture/#sec-security-consideration-td-risks)
    * [10.1.1Thing Description Private Security Data Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-td-private)
    * [10.1.2Thing Description Communication Metadata Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-td-cm)
    * [10.2WoT Scripting API Risks](https://w3c.github.io/wot-architecture/#sec-security-consideration-scripting-risks)
    * [10.2.1Cross-Script Security Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-cross-script)
    * [10.2.2Physical Device Direct Access Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-device-direct-access)
    * [10.3WoT Runtime Risks](https://w3c.github.io/wot-architecture/#sec-security-consideration-runtime-risks)
    * [10.3.1Provisioning and Update Security Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-update-provisioning)
    * [10.3.2Security Credentials Storage Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-credentials-storage)
    * [10.4Trusted Environment Risks](https://w3c.github.io/wot-architecture/#sec-security-consideration-trusted-environment-risks)
    * [10.5Secure Transport](https://w3c.github.io/wot-architecture/#sec-security-consideration-secure-transport)
* Privacy 
    * [11.1WoT Thing Description Risks](https://w3c.github.io/wot-architecture/#sec-privacy-consideration-td-risks)
    * [11.1.1Thing Description Personally Identifiable Information Risk](https://w3c.github.io/wot-architecture/#sec-privacy-consideration-td-pii)
    * [11.2Access to Personally Identifiable Information](https://w3c.github.io/wot-architecture/#arch-privacy-consideration-access-controls)

**Comment by mmccool** [comment]
Test link to threat in S&P Guidelines: https://w3c.github.io/wot-security/ - no, doesn't work, need anchors.

**Comment by mmccool** [comment]
Factor out the above survey of considerations in to a separate file: https://github.com/w3c/wot-security/pull/233

**Comment by mmccool** [comment]
Close this issue, but factor out into other small issues.  A number of the things discussed here have already been taken care of.  Above PR captures survey.     Here is a consolidated list of all the discussion points that have not yet been addressed or for which an issue has not be created:
- Says WoT is declarative, not prescriptive, but some parts now prescriptive
- Does not mention Discovery at all
- Intro section is quite weak, does not define security, and ignores privacy
- Lifecycle needs to be aligned with Arch (or just reference it)
- No references after 2019 (of course), things like OWASP guidelines are published annually
- Should reference protocol bindings for other protocols rather than focusing on CoAP/HTTP/MQTT
- No mention of DID, SSI, other key distribution mechanisms
- End-to-end security mentions TD signing, but we have no good way to do that
- "Secure practices for..." is a bit redundant, can simplify titles
- Protocol-specific comments in secure transport really about TLS/DTLS, which are a separate layer from protocols (e.g. can have OPC UA over these secure transports, too...)
- Need to refactor to figure what goes where in new charter; a lot of overlap with security and privacy considerations in other documents, lifecycle is out of place, etc.

Here are some points that we have already addressed:
- Mentions DoS as a threat, but not DDoS
- "Requirements" section is not really requirements, consider a different name (perhaps "Analysis")

**Comment by mmccool** [comment]
content has been reorganized into other issues/PRs.
