### ISSUE TITLE
Add Material for "Secure Practices for designing WoT Scripts and WoT Script APIs" section

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#22]

**Comment by mmccool** [comment]
Will defer until after FP release.

**Comment by mmccool** [comment]
Zoltan, it would be nice if you could at least just put a paragraph *inside the Editor's note* about what the requirements would be here

**Comment by ereshetova** [comment]
The section for the security practices has been re-arranged and this section doesn't exist anymore. 
Instead "6.3 Secure Practices for designing WoT Interfaces" is added and base recommendations are written. 
The concrete best practices will be written to this section together with others.
