### ISSUE TITLE
Fix definition links to threat model

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#28]
References to items defined outside the threat model section need to be updated to refer to the new names and ReSpec definitions.

**Comment by mmccool** [comment]
Followup to issue https://github.com/w3c/wot-security/issues/16.

**Comment by mmccool** [comment]
Elena to do a final check.   Security Objectives still needs some work.

**Comment by ereshetova** [comment]
Addressed in PR https://github.com/w3c/wot-security/pull/42

**Comment by ereshetova** [comment]
Closing since PR is merged
