### ISSUE TITLE
Use ReSpec markup for figures and definitions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#29]
See also https://github.com/w3c/wot-security/issues/16, where this was done during revision of the threat modelling section (which can be used as a reference for how it should be done...)

**Comment by mmccool** [comment]
Note: this issue is about using ReSpec formatting and linking for ALL figures, not just the ones in the Threat section.

**Comment by mmccool** [comment]
Think this is done now... let's do one more check before release.

**Comment by ereshetova** [comment]
I double checked it now. All good. Closing the issue.
