### ISSUE TITLE
Add a section on "Privacy Considerations"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#36]
Separate section, main points, even if we mention other privacy things separately in the document.  However, this section can refer to issues specifically relevant to privacy, including specific legal requirements.

Dave to create an initial PR - just an Editor's para listing the things we should include.

Need to find a privacy expert - Soumya, perhaps person who presented at last F2F on privacy

**Comment by ereshetova** [comment]
The section has been now added to the document, so closing this issue.
