### ISSUE TITLE
Add Lifecycle discussion

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#39]
Most of the references (IIC, IETF IoT Security State of the Art, etc) on best practices make reference to a security lifecycle.   We should define or refer to a lifecycle, and clarify what parts of the lifecycle the WoT is appropriate for enabling.

The conservative approach would be to say it only applies the "Operational Phase" and not during onboarding, etc.  This is a reasonable place to start (see also Issue https://github.com/w3c/wot-security/issues/15), and if in particular the TD is only provided to already-trusted devices than a certain set of threats will be mitigated.   Longer-term, we may want to look at supporting on-boarding.

In particular, in the pattern where a TD is available from somewhere other than the device, or is available via a special channel (eg a URL provided by a bluetooth beacon), then the TD could include information required to authenticate with/to the device and to help onboard it as a trusted device.  However, if the TD is provided to untrusted devices to assist pre-onboarding discovery, then it may have to be subsetted.

**Comment by ereshetova** [comment]
I think this can be closed now as we do have an initial discussion on lifecycle in the document now. 
Further modifications are pending the arch. document to have its own general lifecycle version
