### ISSUE TITLE
Align Threat model with IETF IoT RFC

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#40]
Review Garcia17, in particular the threat model, and align our terminology.

**Comment by mmccool** [comment]
Elena to review for terminology alignment...

**Comment by ereshetova** [comment]
Aligned in this PR: https://github.com/w3c/wot-security/pull/62

Most of the changes are around stakeholder names and the rest seems to be quite aligned already. When we will be added a lifecycle section, it would need to be aligned also.

**Comment by mmccool** [comment]
Terminology/Threat model is aligned so I will close the issue.  We can reopen another one if more is to be done.  The lifecycle should propbably be a separate issue.
