### ISSUE TITLE
Make links to the standard security terms

### ISSUE THREAD

**Issue by ereshetova** [w3c/wot-security#45]
Is "DOS resistance" a defined term?  If so, where are they defined, and do we need links?

@zolkis:
If defined, we should use links. If not defined, we can use the term as a prose, since the WoT group is not required to give a formal, later referenceable definition of 'DOS resistance'.

@ereshetova:
This was actually a comment from Michael that I haven't yet decided how to handle.
We have a standard set of security terms and I haven't seen an example how one would reference such terms from this doc. Do you have an example of referencing outside term form a WoT doc?

**Comment by zolkis** [comment]
> Do you have an example of referencing outside term form a WoT doc?

- If mentioned once, a single link is fine. 
- If the term is used more than once, we can define an entry in the Terminology section that may contain external links, and later it can find a new home if needed. I would probably use this one for now.
- Also, we can define local biblio entry for it in the document header.

**Comment by mmccool** [comment]
As part of our review of terminology alignment with the Architecture CR (https://github.com/w3c/wot-security/issues/126) we should make a list of terms and put them in a Terminology section.   As a separate step we can worry about tracking an external reference (eg ITU, NIST).

**Comment by mmccool** [comment]
We did add references to ISO specs etc for the PR release of the Arch spec, so if we consider this issue as applying to the 1.0 release it is complete.  We may want to re-open a new issue for version 2.0.
