### ISSUE TITLE
Role of Consent

### ISSUE THREAD

**Issue by jasonanovak** [w3c/wot-security#67]
The Thing User has a security goal of "Don't want their data to be exposed to any other thing user, Thing provider or OEM unless intended (Data confidentiality). Don't want their data to be modified unless intended (Data integrity).”  

It would be worthwhile to include a goal of consent to ensure not just that the user is aware that their data is being shared but also that they consented to it.

**Comment by mmccool** [comment]
Hmmm... this basically should be part of some metadata controlling a data distribution policy for TDs.   It would make sense to include this metadata in the Thing Directory API.   For example, when you register a Thing with a Thing Directory, you could say who has access to that data (and by giving this information, you are not only consenting, you are *directing* the scope of the distribution).   Unfortunately the Thing Directory is currently not in scope in the current charter...

However, the Scripting API *does* have a "scope" for an Exposed Thing that indicates (at a more abstract level) the scope of the Thing's distribution.   We should consider adding some language to the Scripting API (and maybe refine the scope definition) to address this issue.

**Comment by mmccool** [comment]
This has been addressed in the Security and Privacy Considerations document.   Given no further comment, going to close this issue.
