### ISSUE TITLE
Metadata: OpenID Connect

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#75]
Does OpenIDConnect even make sense for IoT devices?  It may make sense for authentication servers, but those generally only be referenced by Things, not running on them.

**Comment by ereshetova** [comment]
Overall I would leave OpenID out for now and until anyone has a good use cases to support it in WoT. I think it would be more relevant to define basic methods first.

**Comment by mmccool** [comment]
In PR https://github.com/w3c/wot-security/pull/86 I have moved OpenIDConnect to a "discussion" section... not part of the main proposal any more.

**Comment by mmccool** [comment]
Going to close this, we can reopen if we feel we should deal with it.
