### ISSUE TITLE
Metadata: Cookie API Keys

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#78]
Does this even make sense for machine to machine IoT APIs?

**Comment by ereshetova** [comment]
Does WoT use cookies anywhere? If not, I don't see a reason for API keys provided in cookies

**Comment by mmccool** [comment]
Cookies are a way to simulate state on stateless servers.   This allows server-side optimizations like redirecting requests through a load balancer to get scaling in web services.  However, for Things, the server is really going to be one device so the arguments for making services stateless are not as strong (although there are some, like DDoS resistance; servers may not have much storage so making the client keep the state makes sense).  The other reason for a cookie is to track clients so the server knows it is the same client that it talked to before, which can be useful (eg it can track preferences, etc. to avoid having the client having to retransmit them every time).

Anyhow, a cookie is just state maintained by the client and there is a place in the HTTP header for it.   It's actually quite logical to use that to transmit an API key rather than as a query parameter or whatever.  Some web services we want to wrap in TDs may do things that way, so we probably should support it.  but it's really just an option for how to transmit API keys from the client to the server (eg another value for "in" under the "apikey" scheme: one of "header", "cookie", or "parameter" (eg in the URL as a query parameter) and maybe "body".   We should look at how web services generally handle/accept API keys to see if I've overlooked any options...

**Comment by mmccool** [comment]
What this boils down to is that we are describing, not prescribing.   If we were prescribing we would just say "API keys should go in the following query parameter" or whatever and we would be done.   But since we are describing, we need to describe all the various ways Things may transmit API keys over HTTP (or other protocols...).   Since there aren't any Things out there yet to look at, we need to look at Web services (although we can also look at AWS IoT, Home Kit, etc. to see how they handle this).   Anyhow, since we know some web services carry API keys in cookies, Things may too (if they follow the same conventions as web services), so we probably *should* support them.

**Comment by mmccool** [comment]
Re not adding to many things at once: I agree re not making the attack surface too large, but I think cookies are used by some web services so we should probably add them.  Eventually we may have to add some websocket things too; I've seen that used for some Things (eg Sonoff devices).   

Re HTTPS being necessary, there is a validation requirement here: certain security configurations should only be used with HTTPS, and use with other protocols should be considered and error and caught and reported somehow.

**Comment by mmccool** [comment]
I found at least one IoT system that uses cookies to manage security: The Intel Building Management Platform.  The API for this, implemented by CANDI Controls, is based on HTTP/JSON... and uses cookies to manage session keys.   It seems like a reasonable thing to want to describe with a TD, so...
https://www.intel.com/content/www/us/en/smart-buildings/building-management-platform/overview.html

**Comment by mmccool** [comment]
Conclusion; YES we need them.   They are in the current metadata proposal.  Need to generate an example, perhaps related (as session keys) in relation to this issue: https://github.com/w3c/wot-security/issues/98.  For example, modelling the Intel BMP will require use of cookies.
