### ISSUE TITLE
Metadata: Proxy

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#81]
A proxy requires a separate URL to access it. A standard tag should be used for this when it is needed. The example from Matthias uses "href". However, should this be embedded in another access scheme, or have its own scheme? For HTTP proxies, do we need to specify anything different from "http"?  What about non-HTTP proxies, eg. specifically for WoT systems?

**Comment by mmccool** [comment]
Zoltan: an explicit example of how schemes and protocols can be combined...

**Comment by mmccool** [comment]
Not sure what schemes and combinations we should look at in the short terms.  At least basic, oauth, and ocf.

**Comment by mmccool** [comment]
Will leave open until I generate and we review a PR with the suggested changes.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-security/pull/86

**Comment by mkovatsc** [comment]
From `"scheme": "basic"` the implementation cannot recognize that a forward proxy is needed. The information is implicitly in the `proxy` field and it is unclear if `basic` now applies to the device or the proxy.

A proxy probably needs to be combined with any other "scheme". So a `proxy` field is good, but we should also have a dedicated `proxyScheme` and probably a `proxyId` to match additional proxy credentials.

**Comment by mmccool** [comment]
The way I have set this up if proxyURL is given the entire configuration is for a proxy.   If it is not given, it is for the endpoint.   The then need to list multiple configurations for all “forms” that use proxies.  This approach lets you use whatever security configuration you want for the proxy and use a completely independent configuration for the endpoint.

I should probably try to clarify the example.

**Comment by mmccool** [comment]
I should comment that in the current proposal you can have multiple configurations using the "basic" scheme, eg. one for an endpoint, one for the proxy.   This is another reason not to use scheme names as "tags" eg <scheme> : <config> in a map, because then you could only use each scheme once.  The proposal (using { "scheme": <scheme>, ... } allows each scheme to be used multiple times.

I do need to improve the writeup now that we've seen some feedback.   I have to generate an HTML-based PR for the TD spec anyway...

**Comment by mkovatsc** [comment]
Within `security` you use `@id` to give an identifier that is used within the form (where we should use something like `useSecurity`). This `@id` would be the key in an object notation (based on JSON-LD 1.1 way of doing things. The updated example would be like:

```
"security": {
     "proxy-config": {
         "scheme": "Basic",
         "proxy": "http://plugfest.thingweb.io:8087"
     },
     "endpoint-config-1": {
         "scheme": "Basic",
         .... // endpoint security config
     }
}
```
Within Interactions:
```
    "form": {
        ...
        "useSecurity": ["proxy-config","endpoint-config-1"],
        ...
     }
```
P.S.: I am still not sure if we should use all lower-case value terms or camel-case for `scheme` values, as the value usually corresponds to an RDF class -- but which can be masked through a JSON-LD term, which is usually lower case...

**Comment by mkovatsc** [comment]
My issue with `proxy` suddenly being the important field to understand the scheme is still not solved.

`scheme` acts basically like the `type` field for DataSchema: its value decides what sub-class applies, and hence what other fields must/can be present.

Thus, `Proxy` should be a scheme on its own that then has something like `proxyScheme`. Maybe `useSecurity` within the security definition might work, but feels complex.

**Comment by mmccool** [comment]
I *think* this is resolved but we should wait until after the Bundang plugfest and implementation feedback from Matthias.   One issue is dealing with both protocol-aware proxies (eg HTTP Proxy) and transparent (application-level) proxies.   These may require different strategies.

**Comment by mmccool** [comment]
Going to close this, consider it done, but can raise new issues after testing.   I propose to add an explicit checkpoint to the plugfest planning document to test that we have the right metadata here, then close this issue.

**Comment by mmccool** [comment]
OK, will really close this now.   I think Matthias' point about the appearance of the "proxy" field should really change the "type" of the scheme is kind of relevant, but I think the rule is clear enough (if "proxy" appears, the scheme is for the proxy).
