### ISSUE TITLE
Metadata: Versions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#85]
Some security schemes may have more than one version and we may want to restrict use to a certain version, or to some version or later.
Do we need to support version restrictions, and if so, how?

**Comment by mkovatsc** [comment]
This should be part of the scheme, as security suite versions are usually pretty stable and comprehensive (e.g., OAuth 2.0, TLS 1.2, ...).

**Comment by mmccool** [comment]
Baking versions into the scheme name (if needed) seems to be the consensus.   I propose we close this issue with that conclusion if there is no other feedback in the next couple of weeks.

**Comment by mmccool** [comment]
CONCLUSION: Bake version numbers into the scheme name (if necessary).  Do not provide a separate versioning mechanism.
